runtime: php55

handlers:
- url: /js/(.+\.js)$
  mime_type: text/javascript
  static_files: js/\1

- url: /app/(.+)
  static_files: app/\1

- url: /css/(.+\.css)$
  mime_type: text/css
  static_files: css/\1

- url: /(.+)
  script: index.php
