runtime: php55

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/mobius-db;dbname=mobius
  MYSQL_USER: mobius
  MYSQL_PASSWORD: ''

handlers:
- url: /js/(.+\.js)$
  mime_type: text/javascript
  static_files: js/\1
  upload: js/(.+\.js)

- url: /app/(.+)
  static_files: app/\1
  upload: app/(.+)

- url: /css/(.+)$
  static_files: css/\1
  upload: css/(.+)$

- url: /.*
  script: index.php
